#include "TPTools/Utils/TPEnum.h"

namespace TP::maths
{
	TP_ENUM_CREATE(InterpolationMethod_e, CONSTANT, LINEAR, QUADRATIC, NATURAL_CUBIC_SPLINE, CLAMBED_CUBIC_SPLINE, CLAMPED_NATUAL_CUBIC_SPLINE,
		MONOTONIC_SPLINE, TP_LOCAL_SPLINE, MONOTONE_CONVEX)
		TP_ENUM_VALUE(CONSTANT, "CONSTANT")
		TP_ENUM_VALUE(LINEAR, "LINEAR")
		TP_ENUM_VALUE(QUADRATIC, "QUADRATIC")
		TP_ENUM_VALUE(NATURAL_CUBIC_SPLINE, "NATURAL_CUBIC_SPLINE")
		TP_ENUM_VALUE(NATURAL_CUBIC_SPLINE, "SPLINE")
		TP_ENUM_VALUE(CLAMBED_CUBIC_SPLINE, "CLAMBED_CUBIC_SPLINE")
		TP_ENUM_VALUE(CLAMPED_NATUAL_CUBIC_SPLINE, "CLAMPED_NATURAL_CUBIC_SPLINE")
		TP_ENUM_VALUE(MONOTONIC_SPLINE, "MONOTONIC_SPLINE")
		TP_ENUM_VALUE(MONOTONIC_SPLINE, "MON_SPLINE")
		TP_ENUM_VALUE(TP_LOCAL_SPLINE, "TP_LOCAL_SPLINE")
		TP_ENUM_VALUE(TP_LOCAL_SPLINE, "LOCAL_SPLINE")
		TP_ENUM_VALUE(MONOTONE_CONVEX, "MONOTONE_CONVEX")
		TP_ENUM_VALUE(MONOTONE_CONVEX, "MONOTONE")
		TP_ENUM_CREATE_END(InterpolationMethod_e)

		TP_ENUM_CREATE(CurveExtrapolationChoice_e, EXTRAPOLATE, FLAT_RATE, FLAT_ZERO_RATE)
		TP_ENUM_VALUE(FLAT_RATE, "FLAT_RATE")
		TP_ENUM_VALUE(EXTRAPOLATE, "EXTRAPOLATE")
		TP_ENUM_VALUE(FLAT_ZERO_RATE, "FLAT_ZERO_RATE")
		TP_ENUM_CREATE_END(CurveExtrapolationChoice_e)

		TP_ENUM_CREATE(CurveInterpolationVariable_e, LOG_DF, FORWARD, NSS)
		TP_ENUM_VALUE(LOG_DF, "LOG_DF")
		TP_ENUM_VALUE(FORWARD, "FORWARD")
		TP_ENUM_VALUE(NSS, "NSS")
		TP_ENUM_VALUE(NSS, "NELSON-SIEGEL")
		TP_ENUM_CREATE_END(CurveInterpolationVariable_e)

		TP_ENUM_CREATE(InterpolationParamName_e, SIGMA)
		TP_ENUM_VALUE(SIGMA, "SIGMA")
		TP_ENUM_VALUE(SIGMA, "S")
		TP_ENUM_CREATE_END(InterpolationParamName_e)


	enum class InterpolationMethod
	{
		CONSTANT,
		LINEAR,
		QUADRATIC,
		NATURAL_CUBIC_SPLINE,
		CLAMBED_CUBIC_SPLINE,
		CLAMPED_NATUAL_CUBIC_SPLINE,
		MONOTONIC_SPLINE,
		TP_LOCAL_SPLINE,
		MONOTONE_CONVEX
	};

	enum class ExtrapolationType
	{
		CONSTANT,
		LINEAR
	};


}